name: Build binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  binaries:
    name: Build binaries
    strategy:
      matrix:
        rust: [
          1.55.0,
          stable
        ]
        bin: [
          farcasterd,
          peerd,
          swapd,
          walletd,
          syncerd,
          swap-cli
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y libsqlite3-dev libssl-dev libzmq3-dev pkg-config build-essential cmake

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: Rust cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: bin-${{ matrix.bin }}

      - name: Build ${{ matrix.bin }} daemon
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin ${{ matrix.bin }} --all-features
