name: Create packages

on:
  push:
    branches: [ main ]

jobs:
  faracsterd_container:
    name: Farcasterd Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker build
      run: docker build -f $GITHUB_WORKSPACE/Dockerfile -t ghcr.io/farcaster-project/farcaster-node/farcasterd:latest $GITHUB_WORKSPACE

    - name: Docker push to GitHub Packages
      run: docker push ghcr.io/farcaster-project/farcaster-node/farcasterd:latest
